// SpacetimeDB client — the single connection that owns balances, transactions and
// notifications for the web service. (The Node bot reaches it over localhost HTTP.)
//
// Matches the `spacetimedb` unified SDK shipped with CLI 2.6:
//   • builder: .withUri().withDatabaseName().withToken().onConnect().build()
//   • reducers: conn.reducers.<camelCase>(...)  (call only; no per-reducer result event)
//   • tables:  conn.db.account.onInsert/onUpdate/onDelete + .iter()
//   • subs:    conn.subscriptionBuilder().onApplied().subscribe([SQL])
//
// Because the SDK gives no reducer-result callback, correctness comes from:
//   1. a pre-check against the live balance cache (reject "insufficient" before calling),
//   2. per-user serialization upstream (client busy-flag + per-user rate limit),
//   3. the global `account` subscription, which reconciles the cache from the server.
//
// `./module_bindings` is generated by `spacetime generate --lang typescript`.

import { DbConnection } from "./module_bindings";

type BalCb = (balance: number) => void;
type NotifRow = { owner: string; kind: string; amount: number | bigint; fromTag: string; msg: string; ts: number | bigint; read: boolean };
type NotifCb = (n: NotifRow) => void;

function num(v: number | bigint): number { return typeof v === "bigint" ? Number(v) : v; }

export class Stdb {
  private conn: any;
  private connected = false;
  private balances = new Map<string, number>();
  private banks = new Map<string, number>();
  private notifs = new Map<string, NotifRow[]>();
  private notifSub = new Map<string, { handle: any; refs: number }>();
  private balCbs = new Map<string, Set<BalCb>>();
  private bankCbs = new Map<string, Set<BalCb>>();
  private notifCbs = new Map<string, Set<NotifCb>>();
  private readyP?: Promise<void>;

  constructor(private uri: string, private moduleName: string, private token?: string) {}

  ready(): Promise<void> { if (!this.readyP) this.readyP = this.#connect(); return this.readyP; }

  #connect(): Promise<void> {
    return new Promise((resolve, reject) => {
      let b = DbConnection.builder()
        .withUri(this.uri)
        .withDatabaseName(this.moduleName)
        .onConnect((conn: any) => {
          this.connected = true;
          conn.db.account.onInsert((_c: any, r: any) => this.#setBal(r.owner, num(r.balance)));
          conn.db.account.onUpdate((_c: any, _o: any, n: any) => this.#setBal(n.owner, num(n.balance)));
          // The codegen camelCases reducers (settleWin) but may keep snake_case table
          // accessors (server_bank) — resolve whichever name exists so the bank cache
          // actually populates. (This mismatch was leaving the bank stuck at 0.)
          const bank = this.#bankTable(conn);
          if (!bank) { try { console.warn("[stdb] server_bank table accessor not found. conn.db keys:", Object.keys(conn.db || {}).join(", ")); } catch {} }
          bank?.onInsert?.((_c: any, r: any) => this.#setBank(r.gid, num(r.balance)));
          bank?.onUpdate?.((_c: any, _o: any, n: any) => this.#setBank(n.gid, num(n.balance)));
          // account gates ready(); server_bank is its own subscription so a multi-query
          // quirk can't stop bank rows from syncing. Seed both caches from iter() on apply.
          conn.subscriptionBuilder().onApplied(() => { this.#seedBanks(conn); resolve(); }).subscribe(["SELECT * FROM account"]);
          try { conn.subscriptionBuilder().onApplied(() => this.#seedBanks(conn)).subscribe(["SELECT * FROM server_bank"]); } catch {}
        })
        .onConnectError((_c: any, e: any) => reject(e instanceof Error ? e : new Error(e?.message || String(e))))
        .onDisconnect(() => { this.connected = false; this.readyP = undefined; setTimeout(() => this.ready().catch(() => {}), 1500); });
      if (this.token) b = b.withToken(this.token);
      this.conn = b.build();
    });
  }

  #setBal(owner: string, balance: number) {
    this.balances.set(owner, balance);
    const cbs = this.balCbs.get(owner);
    if (cbs) for (const cb of cbs) try { cb(balance); } catch {}
  }

  #setBank(gid: string, balance: number) {
    this.banks.set(gid, balance);
    const cbs = this.bankCbs.get(gid);
    if (cbs) for (const cb of cbs) try { cb(balance); } catch {}
  }

  // Resolve the server_bank table accessor regardless of codegen casing.
  #bankTable(conn: any): any { return conn?.db?.serverBank ?? conn?.db?.server_bank ?? conn?.db?.serverbank ?? null; }

  // Reconcile the bank cache from whatever rows the server_bank subscription holds.
  #seedBanks(conn: any) {
    try { for (const r of this.#bankTable(conn)?.iter?.() ?? []) this.#setBank(r.gid, num(r.balance)); } catch {}
  }

  // Resolve once `owner`'s balance row changes (server reconciliation), or after `ms`.
  #waitChange(owner: string, ms = 1500): Promise<void> {
    return new Promise((resolve) => {
      let done = false;
      const off = this.onBalance(owner, () => { if (!done) { done = true; off(); clearTimeout(t); resolve(); } });
      const t = setTimeout(() => { if (!done) { done = true; off(); resolve(); } }, ms);
    });
  }

  getBalance(owner: string): number { return this.balances.get(owner) ?? 0; }

  // Total FC in circulation (sum of all positive balances + server banks) — the money
  // supply. FC-T's price tracks this, so it reflects how many Fluxer coins exist (like
  // USD-T tracking dollar reserves). Includes server banks (tax accruals) since that FC
  // exists too — it's just held by the server, not destroyed.
  totalSupply(): number {
    let total = 0;
    for (const balance of this.balances.values()) if (balance > 0) total += balance;
    for (const bank of this.banks.values()) if (bank > 0) total += bank;
    return total;
  }

  // Top-N holders by balance (for the &leaderboard command). Reads the in-memory cache
  // kept fresh by the `account` table subscription. Balances are authoritative in STDB,
  // NOT Mongo — Mongo's `bal` field is a stale starter that's never updated, which is why
  // the old leaderboard showed everyone at 1000.
  topBalances(limit: number): Array<{ owner: string; balance: number }> {
    const out: Array<{ owner: string; balance: number }> = [];
    for (const [owner, balance] of this.balances) if (balance > 0) out.push({ owner, balance });
    out.sort((a, b) => b.balance - a.balance);
    return out.slice(0, Math.max(1, Math.min(limit || 10, 100)));
  }

  // ── reducer calls — args as an OBJECT (camelCase keys, matching the codegen).
  //    The call returns a Promise: resolves on commit, rejects (SenderError) on a
  //    server-side error (e.g. "insufficient"). We await it for the authoritative
  //    result; the `account` subscription keeps getBalance fresh for reads/WS.
  async #call(name: string, args: Record<string, any>): Promise<void> {
    await this.ready();
    const fn = this.conn?.reducers?.[name];
    if (typeof fn !== "function") throw new Error(`reducer ${name} not deployed (republish + regenerate bindings)`);
    try { await fn.call(this.conn.reducers, args); }
    catch (e: any) { throw new Error(e?.message || String(e)); }
  }
  async ensureAccount(owner: string) { await this.#call("ensureAccount", { owner }).catch(() => {}); }
  async credit(owner: string, amount: number) { return this.#call("credit", { owner, amount: BigInt(Math.floor(amount)) }); }
  async deduct(owner: string, amount: number) { return this.#call("deduct", { owner, amount: BigInt(Math.floor(amount)) }); }
  async settle(owner: string, bet: number, payout: number) { return this.#call("settle", { owner, bet: BigInt(Math.floor(bet)), payout: BigInt(Math.floor(payout)) }); }
  async settleWin(owner: string, bet: number, payout: number, gid: string, tax: number) { return this.#call("settleWin", { owner, bet: BigInt(Math.floor(bet)), payout: BigInt(Math.floor(payout)), gid: gid || "", tax: BigInt(Math.max(0, Math.floor(tax))) }); }
  async creditWin(owner: string, gross: number, gid: string, tax: number) { return this.#call("creditWin", { owner, gross: BigInt(Math.floor(gross)), gid: gid || "", tax: BigInt(Math.max(0, Math.floor(tax))) }); }
  async bankSpend(gid: string, amount: number) { return this.#call("bankSpend", { gid, amount: BigInt(Math.floor(amount)) }); }
  async bankSet(gid: string, balance: number) { return this.#call("bankSet", { gid, balance: BigInt(Math.max(0, Math.floor(balance))) }); }
  async transfer(from: string, to: string, amount: number, fromTag: string) { return this.#call("transfer", { from, to, amount: BigInt(Math.floor(amount)), fromTag }); }
  async setExact(owner: string, balance: number) { return this.#call("setExact", { owner, balance: BigInt(Math.floor(balance)) }); }
  async addNotification(owner: string, kind: string, amount: number, fromTag: string, msg: string) { return this.#call("addNotification", { owner, kind, amount: BigInt(Math.floor(amount)), fromTag, msg }).catch(() => {}); }
  async markRead(owner: string) { return this.#call("markRead", { owner }).catch(() => {}); }

  // ── balance push listeners (for WS) ────────────────────────────────────────
  onBalance(owner: string, cb: BalCb): () => void {
    const s = this.balCbs.get(owner) ?? new Set(); s.add(cb); this.balCbs.set(owner, s);
    return () => { s.delete(cb); if (!s.size) this.balCbs.delete(owner); };
  }

  // ── per-server bank (subscribed globally; read from cache) ──────────────────
  getServerBank(gid: string): number { return this.banks.get(gid) ?? 0; }
  onBank(gid: string, cb: BalCb): () => void {
    const s = this.bankCbs.get(gid) ?? new Set(); s.add(cb); this.bankCbs.set(gid, s);
    return () => { s.delete(cb); if (!s.size) this.bankCbs.delete(gid); };
  }

  // ── per-user notifications (subscribed on demand) ──────────────────────────
  async subscribeNotifs(owner: string): Promise<void> {
    // `owner` is concatenated into the subscription SQL — only allow the Discord id
    // shape (digits) so nothing else can be injected even if a caller is mis-wired.
    if (!/^\d{1,20}$/.test(owner)) throw new Error("bad owner");
    await this.ready();
    const ex = this.notifSub.get(owner);
    if (ex) { ex.refs++; return; }
    await new Promise<void>((resolve) => {
      const handle = this.conn.subscriptionBuilder()
        .onApplied(() => { this.#refreshNotifCache(owner); resolve(); })
        .subscribe([`SELECT * FROM notification WHERE owner = '${owner}'`]);
      this.conn.db.notification.onInsert((_c: any, r: any) => { if (r.owner === owner) { this.#refreshNotifCache(owner); this.#emitNotif(owner, r); } });
      this.conn.db.notification.onUpdate((_c: any, _o: any, n: any) => { if (n.owner === owner) this.#refreshNotifCache(owner); });
      this.conn.db.notification.onDelete((_c: any, r: any) => { if (r.owner === owner) this.#refreshNotifCache(owner); });
      this.notifSub.set(owner, { handle, refs: 1 });
    });
  }
  unsubscribeNotifs(owner: string) {
    const ex = this.notifSub.get(owner); if (!ex) return;
    if (--ex.refs <= 0) { try { ex.handle?.unsubscribe?.(); } catch {} this.notifSub.delete(owner); this.notifs.delete(owner); }
  }
  #refreshNotifCache(owner: string) {
    const rows: NotifRow[] = [];
    for (const r of this.conn.db.notification.iter() as any) if (r.owner === owner) rows.push(r);
    rows.sort((a, b) => num(b.ts) - num(a.ts));
    this.notifs.set(owner, rows);
  }
  #emitNotif(owner: string, r: NotifRow) { const cbs = this.notifCbs.get(owner); if (cbs) for (const cb of cbs) try { cb(r); } catch {} }
  onNotification(owner: string, cb: NotifCb): () => void {
    const s = this.notifCbs.get(owner) ?? new Set(); s.add(cb); this.notifCbs.set(owner, s);
    return () => { s.delete(cb); if (!s.size) this.notifCbs.delete(owner); };
  }
  async getNotifications(owner: string): Promise<{ items: any[]; unread: number }> {
    await this.subscribeNotifs(owner);
    const rows = this.notifs.get(owner) ?? [];
    const items = rows.map(r => ({ t: r.kind, m: r.msg, a: num(r.amount), f: r.fromTag, ts: num(r.ts), read: r.read }));
    return { items, unread: items.filter(i => !i.read).length };
  }
}
