// SpacetimeDB client — the single connection that owns balances, transactions and
// notifications for the web service. (The Node bot reaches it over localhost HTTP.)
//
// Matches the `spacetimedb` unified SDK shipped with CLI 2.6:
//   • builder: .withUri().withDatabaseName().withToken().onConnect().build()
//   • reducers: conn.reducers.<camelCase>(...)  (call only; no per-reducer result event)
//   • tables:  conn.db.account.onInsert/onUpdate/onDelete + .iter()
//   • subs:    conn.subscriptionBuilder().onApplied().subscribe([SQL])
//
// Because the SDK gives no reducer-result callback, correctness comes from:
//   1. a pre-check against the live balance cache (reject "insufficient" before calling),
//   2. per-user serialization upstream (client busy-flag + per-user rate limit),
//   3. the global `account` subscription, which reconciles the cache from the server.
//
// `./module_bindings` is generated by `spacetime generate --lang typescript`.

import { DbConnection } from "./module_bindings";

type BalCb = (balance: number) => void;
type NotifRow = { owner: string; kind: string; amount: number | bigint; fromTag: string; msg: string; ts: number | bigint; read: boolean };
type NotifCb = (n: NotifRow) => void;

function num(v: number | bigint): number { return typeof v === "bigint" ? Number(v) : v; }

export class Stdb {
  private conn: any;
  private connected = false;
  private balances = new Map<string, number>();
  private notifs = new Map<string, NotifRow[]>();
  private notifSub = new Map<string, { handle: any; refs: number }>();
  private balCbs = new Map<string, Set<BalCb>>();
  private notifCbs = new Map<string, Set<NotifCb>>();
  private readyP?: Promise<void>;

  constructor(private uri: string, private moduleName: string, private token?: string) {}

  ready(): Promise<void> { if (!this.readyP) this.readyP = this.#connect(); return this.readyP; }

  #connect(): Promise<void> {
    return new Promise((resolve, reject) => {
      let b = DbConnection.builder()
        .withUri(this.uri)
        .withDatabaseName(this.moduleName)
        .onConnect((conn: any) => {
          this.connected = true;
          conn.db.account.onInsert((_c: any, r: any) => this.#setBal(r.owner, num(r.balance)));
          conn.db.account.onUpdate((_c: any, _o: any, n: any) => this.#setBal(n.owner, num(n.balance)));
          conn.subscriptionBuilder().onApplied(() => resolve()).subscribe(["SELECT * FROM account"]);
        })
        .onConnectError((_c: any, e: any) => reject(e instanceof Error ? e : new Error(e?.message || String(e))))
        .onDisconnect(() => { this.connected = false; this.readyP = undefined; setTimeout(() => this.ready().catch(() => {}), 1500); });
      if (this.token) b = b.withToken(this.token);
      this.conn = b.build();
    });
  }

  #setBal(owner: string, balance: number) {
    this.balances.set(owner, balance);
    const cbs = this.balCbs.get(owner);
    if (cbs) for (const cb of cbs) try { cb(balance); } catch {}
  }

  // Resolve once `owner`'s balance row changes (server reconciliation), or after `ms`.
  #waitChange(owner: string, ms = 1500): Promise<void> {
    return new Promise((resolve) => {
      let done = false;
      const off = this.onBalance(owner, () => { if (!done) { done = true; off(); clearTimeout(t); resolve(); } });
      const t = setTimeout(() => { if (!done) { done = true; off(); resolve(); } }, ms);
    });
  }

  getBalance(owner: string): number { return this.balances.get(owner) ?? 0; }

  // ── reducer calls — args as an OBJECT (camelCase keys, matching the codegen).
  //    The call returns a Promise: resolves on commit, rejects (SenderError) on a
  //    server-side error (e.g. "insufficient"). We await it for the authoritative
  //    result; the `account` subscription keeps getBalance fresh for reads/WS.
  async #call(name: string, args: Record<string, any>): Promise<void> {
    await this.ready();
    try { await this.conn.reducers[name](args); }
    catch (e: any) { throw new Error(e?.message || String(e)); }
  }
  async ensureAccount(owner: string) { await this.#call("ensureAccount", { owner }).catch(() => {}); }
  async credit(owner: string, amount: number) { return this.#call("credit", { owner, amount: BigInt(Math.floor(amount)) }); }
  async deduct(owner: string, amount: number) { return this.#call("deduct", { owner, amount: BigInt(Math.floor(amount)) }); }
  async settle(owner: string, bet: number, payout: number) { return this.#call("settle", { owner, bet: BigInt(Math.floor(bet)), payout: BigInt(Math.floor(payout)) }); }
  async transfer(from: string, to: string, amount: number, fromTag: string) { return this.#call("transfer", { from, to, amount: BigInt(Math.floor(amount)), fromTag }); }
  async setExact(owner: string, balance: number) { return this.#call("setExact", { owner, balance: BigInt(Math.floor(balance)) }); }
  async addNotification(owner: string, kind: string, amount: number, fromTag: string, msg: string) { return this.#call("addNotification", { owner, kind, amount: BigInt(Math.floor(amount)), fromTag, msg }).catch(() => {}); }
  async markRead(owner: string) { return this.#call("markRead", { owner }).catch(() => {}); }

  // ── balance push listeners (for WS) ────────────────────────────────────────
  onBalance(owner: string, cb: BalCb): () => void {
    const s = this.balCbs.get(owner) ?? new Set(); s.add(cb); this.balCbs.set(owner, s);
    return () => { s.delete(cb); if (!s.size) this.balCbs.delete(owner); };
  }

  // ── per-user notifications (subscribed on demand) ──────────────────────────
  async subscribeNotifs(owner: string): Promise<void> {
    await this.ready();
    const ex = this.notifSub.get(owner);
    if (ex) { ex.refs++; return; }
    await new Promise<void>((resolve) => {
      const handle = this.conn.subscriptionBuilder()
        .onApplied(() => { this.#refreshNotifCache(owner); resolve(); })
        .subscribe([`SELECT * FROM notification WHERE owner = '${owner.replace(/'/g, "")}'`]);
      this.conn.db.notification.onInsert((_c: any, r: any) => { if (r.owner === owner) { this.#refreshNotifCache(owner); this.#emitNotif(owner, r); } });
      this.conn.db.notification.onUpdate((_c: any, _o: any, n: any) => { if (n.owner === owner) this.#refreshNotifCache(owner); });
      this.conn.db.notification.onDelete((_c: any, r: any) => { if (r.owner === owner) this.#refreshNotifCache(owner); });
      this.notifSub.set(owner, { handle, refs: 1 });
    });
  }
  unsubscribeNotifs(owner: string) {
    const ex = this.notifSub.get(owner); if (!ex) return;
    if (--ex.refs <= 0) { try { ex.handle?.unsubscribe?.(); } catch {} this.notifSub.delete(owner); this.notifs.delete(owner); }
  }
  #refreshNotifCache(owner: string) {
    const rows: NotifRow[] = [];
    for (const r of this.conn.db.notification.iter() as any) if (r.owner === owner) rows.push(r);
    rows.sort((a, b) => num(b.ts) - num(a.ts));
    this.notifs.set(owner, rows);
  }
  #emitNotif(owner: string, r: NotifRow) { const cbs = this.notifCbs.get(owner); if (cbs) for (const cb of cbs) try { cb(r); } catch {} }
  onNotification(owner: string, cb: NotifCb): () => void {
    const s = this.notifCbs.get(owner) ?? new Set(); s.add(cb); this.notifCbs.set(owner, s);
    return () => { s.delete(cb); if (!s.size) this.notifCbs.delete(owner); };
  }
  async getNotifications(owner: string): Promise<{ items: any[]; unread: number }> {
    await this.subscribeNotifs(owner);
    const rows = this.notifs.get(owner) ?? [];
    const items = rows.map(r => ({ t: r.kind, m: r.msg, a: num(r.amount), f: r.fromTag, ts: num(r.ts), read: r.read }));
    return { items, unread: items.filter(i => !i.read).length };
  }
}
